<!-- This code was generated by Builder.io -->
<template>
  <div class="flex flex-col items-center bg-stone-50 rounded-[30px]">
    <div
      class="flex overflow-hidden relative flex-col self-stretch pb-12 w-full whitespace-nowrap min-h-[688px] max-md:max-w-full">
      <img loading="lazy"
        srcSet="https://cdn.builder.io/api/v1/image/assets/TEMP/2782abe7edcf3748866ad2222e8f2c67e9d7f1fe66189de1ce41acf4195e66cb?apiKey=023108a9c99043f18acff792c7e6bb89&width=100 100w, https://cdn.builder.io/api/v1/image/assets/TEMP/2782abe7edcf3748866ad2222e8f2c67e9d7f1fe66189de1ce41acf4195e66cb?apiKey=023108a9c99043f18acff792c7e6bb89&width=200 200w, https://cdn.builder.io/api/v1/image/assets/TEMP/2782abe7edcf3748866ad2222e8f2c67e9d7f1fe66189de1ce41acf4195e66cb?apiKey=023108a9c99043f18acff792c7e6bb89&width=400 400w, https://cdn.builder.io/api/v1/image/assets/TEMP/2782abe7edcf3748866ad2222e8f2c67e9d7f1fe66189de1ce41acf4195e66cb?apiKey=023108a9c99043f18acff792c7e6bb89&width=800 800w, https://cdn.builder.io/api/v1/image/assets/TEMP/2782abe7edcf3748866ad2222e8f2c67e9d7f1fe66189de1ce41acf4195e66cb?apiKey=023108a9c99043f18acff792c7e6bb89&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets/TEMP/2782abe7edcf3748866ad2222e8f2c67e9d7f1fe66189de1ce41acf4195e66cb?apiKey=023108a9c99043f18acff792c7e6bb89&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets/TEMP/2782abe7edcf3748866ad2222e8f2c67e9d7f1fe66189de1ce41acf4195e66cb?apiKey=023108a9c99043f18acff792c7e6bb89&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets/TEMP/2782abe7edcf3748866ad2222e8f2c67e9d7f1fe66189de1ce41acf4195e66cb?apiKey=023108a9c99043f18acff792c7e6bb89"
        class="object-cover absolute inset-0 size-full" />
      <div
        class="flex relative gap-5 justify-between px-20 py-6 mb-96 w-full shadow-2xl bg-black bg-opacity-10 max-md:flex-wrap max-md:px-5 max-md:mb-10 max-md:max-w-full">
        <div class="flex-auto my-auto text-4xl font-medium leading-10 text-white">
          JIVIKA
        </div>
        <div class="flex gap-5 justify-between text-lg max-md:flex-wrap max-md:max-w-full">
          <div class="flex gap-5 justify-between my-auto text-white leading-[150%] max-md:flex-wrap max-md:max-w-full">
            <div class="grow">Service</div>
            <div>Customer</div>
            <div>Blogs</div>
            <div>About</div>
            <div class="grow">Contact</div>
          </div>
          <div class="flex gap-5 justify-between pl-6 font-bold text-center leading-[100%] text-white text-opacity-90">
            <div class="my-auto">Register</div>
            <div class="grow justify-center px-6 py-5 bg-blue-600 shadow-sm rounded-[30px] max-md:px-5">
              Login
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="mt-20 text-4xl font-medium leading-10 whitespace-nowrap text-zinc-900 max-md:mt-10">
      How it work
    </div>
    <div class="mt-3 text-lg leading-7 text-neutral-800 max-md:max-w-full">
      Learn from Industry Experts and Enhance Your Skills.
    </div>
    <div class="flex gap-5 justify-between mt-10 text-lg leading-5 text-center whitespace-nowrap">
      <div class="grow justify-center px-9 py-6 font-bold text-white bg-blue-600 rounded-[40px] max-md:px-5">
        Customer
      </div>
      <div
        class="grow justify-center px-9 py-6 text-blue-600 bg-white border border-solid border-[color:var(--Foundation-Blue-blue-300,#707B9E)] rounded-[36.55px] max-md:px-5">
        Freelancer
      </div>
    </div>
    <div class="px-5 mt-12 w-full max-w-[1234px] max-md:mt-10 max-md:max-w-full">
      <div class="flex gap-5 max-md:flex-col max-md:gap-0 max-md:">
        <div class="flex flex-col w-3/12 max-md:ml-0 max-md:w-full">
          <div class="flex flex-col px-4 py-6 w-full rounded-xl bg-stone-50 max-md:mt-5">
            <div
              class="flex justify-center items-center self-center px-5 bg-blue-600 aspect-square h-[72px] rounded-[80px] w-[72px]">
              <img loading="lazy"
                src="https://cdn.builder.io/api/v1/image/assets/TEMP/bbeb3cf5532e8c06d332ab5425ce69ad5f1cdb09b9d85e5a0c728d8ba8092a5b?apiKey=023108a9c99043f18acff792c7e6bb89"
                class="w-full aspect-square" />
            </div>
            <div class="mt-6 text-lg font-medium leading-7 text-center lowercase text-zinc-900">
              Search fashion
              <span class="lowercase">AND LIFESTYLE FREELANCERS</span>
            </div>
            <div class="mt-3 text-sm leading-5 text-center text-gray-500">
              Download our app to search and find fashion and lifestyle
              freelancers.
            </div>
          </div>
        </div>
        <div class="flex flex-col ml-5 w-3/12 max-md:ml-0 max-md:w-full">
          <div class="flex flex-col px-4 py-6 w-full bg-white rounded-xl shadow-2xl max-md:mt-5">
            <div
              class="flex justify-center items-center self-center px-5 bg-blue-600 aspect-square h-[72px] rounded-[80px] w-[72px]">
              <img loading="lazy"
                src="https://cdn.builder.io/api/v1/image/assets/TEMP/25ad57dbad31d468cc95c61bd0d6890e51cdc6b8f8d5db1004e74e03f5af3c63?apiKey=023108a9c99043f18acff792c7e6bb89"
                class="w-full aspect-square" />
            </div>
            <div class="mt-6 text-lg font-medium leading-7 text-center lowercase text-zinc-900">
              <span class="uppercase">S</span>ELECT &<span class="uppercase">
                c</span>HOOSE SERVICE LOCATION
            </div>
            <div class="mt-3 text-sm leading-5 text-center text-gray-500">
              Filter & Select based on prices availability and ratings.
            </div>
          </div>
        </div>
        <div class="flex flex-col ml-5 w-3/12 max-md:ml-0 max-md:w-full">
          <div class="flex flex-col px-4 py-6 w-full rounded-xl bg-stone-50 max-md:mt-5">
            <div
              class="flex justify-center items-center self-center px-5 bg-blue-600 aspect-square h-[72px] rounded-[80px] w-[72px]">
              <img loading="lazy"
                src="https://cdn.builder.io/api/v1/image/assets/TEMP/0cd1ede51fc4de6362451b78d4ada0c5e2a6eee528f6f0c0b2c8d3a547ec445d?apiKey=023108a9c99043f18acff792c7e6bb89"
                class="w-full aspect-square" />
            </div>
            <div class="mt-6 text-lg font-medium leading-7 text-center lowercase text-zinc-900">
              <span class="uppercase">N</span>EGOTIATE AND PAY<br />
            </div>
            <div class="mt-3 text-sm leading-5 text-center text-gray-500">
              Chat or negotiate with freelancer, and pay off the app.
            </div>
          </div>
        </div>
        <div class="flex flex-col ml-5 w-3/12 max-md:ml-0 max-md:w-full">
          <div class="flex flex-col grow px-4 py-6 w-full rounded-xl bg-stone-50 max-md:mt-5">
            <div
              class="flex justify-center items-center self-center px-5 bg-blue-600 aspect-square h-[72px] rounded-[80px] w-[72px]">
              <img loading="lazy"
                src="https://cdn.builder.io/api/v1/image/assets/TEMP/e16ab4922fa49e41275a19ba152a48eca5a7a52d95db46a3fd01f0bf15054cb7?apiKey=023108a9c99043f18acff792c7e6bb89"
                class="w-full aspect-square" />
            </div>
            <div class="mt-6 text-lg font-medium leading-7 text-center lowercase text-zinc-900">
              <span class="uppercase">E</span>NJOY SERVICE<br />
            </div>
            <div class="mt-3 text-sm leading-5 text-center text-gray-500">
              Enjoy your selected fashion and lifestyle service, and rate your
              freelancer.
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="mt-12 text-4xl font-medium leading-10 whitespace-nowrap text-zinc-900 max-md:mt-10">
      Nearest service
    </div>
    <div class="mt-3 text-lg leading-7 text-neutral-800 max-md:max-w-full">
      Learn from Industry Experts and Enhance Your Skills.
    </div>
    <div class="flex flex-col self-stretch pt-12 mt-8 w-full bg-neutral-100 max-md:max-w-full">
      <div class="self-center mt-1.5 w-full max-w-[1284px] max-md:max-w-full">
        <div class="flex gap-5 max-md:flex-col max-md:gap-0 max-md:">
          <div class="flex flex-col w-[43%] max-md:ml-0 max-md:w-full">
            <div class="flex flex-col grow pb-5 font-medium max-md:mt-10 max-md:max-w-full">
              <div class="flex gap-4 px-5 text-lg leading-5 text-stone-500 max-md:flex-wrap max-md:max-w-full">
                <div class="flex flex-col flex-1 justify-center p-4 rounded-lg border border-solid border-zinc-300">
                  <div class="flex gap-5 justify-between">
                    <div class="my-auto">⭐ 4.5</div>
                    <img loading="lazy"
                      src="https://cdn.builder.io/api/v1/image/assets/TEMP/c6c658011f20a4123634853c60cc632fc3e65890e1e3676d614688838246f750?apiKey=023108a9c99043f18acff792c7e6bb89"
                      class="w-6 aspect-square" />
                  </div>
                </div>
                <div class="flex flex-col flex-1 justify-center p-4 rounded-lg border border-solid border-zinc-300">
                  <div class="flex gap-5 justify-between">
                    <div class="my-auto">50m - 85m</div>
                    <img loading="lazy"
                      src="https://cdn.builder.io/api/v1/image/assets/TEMP/c6c658011f20a4123634853c60cc632fc3e65890e1e3676d614688838246f750?apiKey=023108a9c99043f18acff792c7e6bb89"
                      class="w-6 aspect-square" />
                  </div>
                </div>
                <div class="flex flex-col flex-1 justify-center p-4 rounded-lg border border-solid border-zinc-300">
                  <div class="flex gap-5 justify-between">
                    <div class="flex-auto my-auto">₹500 - ₹850</div>
                    <img loading="lazy"
                      src="https://cdn.builder.io/api/v1/image/assets/TEMP/c6c658011f20a4123634853c60cc632fc3e65890e1e3676d614688838246f750?apiKey=023108a9c99043f18acff792c7e6bb89"
                      class="w-6 aspect-square" />
                  </div>
                </div>
              </div>
              <div class="flex flex-col justify-center p-2.5 mt-10 rounded-lg bg-zinc-50 max-md:mt-10 max-md:max-w-full">
                <div class="flex gap-5 justify-between px-px max-md:flex-wrap max-md:max-w-full">
                  <div class="flex flex-col self-start">
                    <div class="text-lg leading-5 text-center text-blue-600">
                      Family Photographer
                    </div>
                    <div class="flex gap-1 justify-between mt-2.5 text-sm leading-5 text-stone-500">
                      <div class="my-auto w-3 h-3 bg-lime-600 rounded-full"></div>
                      <div class="flex-auto">45 freelancer</div>
                    </div>
                    <img loading="lazy"
                      srcSet="https://cdn.builder.io/api/v1/image/assets/TEMP/1fb340996da9f299f9233acfb501c251782fcac71bd39e51b1cb3f9384b66688?apiKey=023108a9c99043f18acff792c7e6bb89&width=100 100w, https://cdn.builder.io/api/v1/image/assets/TEMP/1fb340996da9f299f9233acfb501c251782fcac71bd39e51b1cb3f9384b66688?apiKey=023108a9c99043f18acff792c7e6bb89&width=200 200w, https://cdn.builder.io/api/v1/image/assets/TEMP/1fb340996da9f299f9233acfb501c251782fcac71bd39e51b1cb3f9384b66688?apiKey=023108a9c99043f18acff792c7e6bb89&width=400 400w, https://cdn.builder.io/api/v1/image/assets/TEMP/1fb340996da9f299f9233acfb501c251782fcac71bd39e51b1cb3f9384b66688?apiKey=023108a9c99043f18acff792c7e6bb89&width=800 800w, https://cdn.builder.io/api/v1/image/assets/TEMP/1fb340996da9f299f9233acfb501c251782fcac71bd39e51b1cb3f9384b66688?apiKey=023108a9c99043f18acff792c7e6bb89&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets/TEMP/1fb340996da9f299f9233acfb501c251782fcac71bd39e51b1cb3f9384b66688?apiKey=023108a9c99043f18acff792c7e6bb89&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets/TEMP/1fb340996da9f299f9233acfb501c251782fcac71bd39e51b1cb3f9384b66688?apiKey=023108a9c99043f18acff792c7e6bb89&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets/TEMP/1fb340996da9f299f9233acfb501c251782fcac71bd39e51b1cb3f9384b66688?apiKey=023108a9c99043f18acff792c7e6bb89"
                      class="mt-2.5 max-w-full aspect-[3.23] w-[116px]" />
                  </div>
                  <img loading="lazy"
                    srcSet="https://cdn.builder.io/api/v1/image/assets/TEMP/6839c253354f236fbfcf67fd275938cc748419b6ee20ad5356d5b0ffa9c7f84c?apiKey=023108a9c99043f18acff792c7e6bb89&width=100 100w, https://cdn.builder.io/api/v1/image/assets/TEMP/6839c253354f236fbfcf67fd275938cc748419b6ee20ad5356d5b0ffa9c7f84c?apiKey=023108a9c99043f18acff792c7e6bb89&width=200 200w, https://cdn.builder.io/api/v1/image/assets/TEMP/6839c253354f236fbfcf67fd275938cc748419b6ee20ad5356d5b0ffa9c7f84c?apiKey=023108a9c99043f18acff792c7e6bb89&width=400 400w, https://cdn.builder.io/api/v1/image/assets/TEMP/6839c253354f236fbfcf67fd275938cc748419b6ee20ad5356d5b0ffa9c7f84c?apiKey=023108a9c99043f18acff792c7e6bb89&width=800 800w, https://cdn.builder.io/api/v1/image/assets/TEMP/6839c253354f236fbfcf67fd275938cc748419b6ee20ad5356d5b0ffa9c7f84c?apiKey=023108a9c99043f18acff792c7e6bb89&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets/TEMP/6839c253354f236fbfcf67fd275938cc748419b6ee20ad5356d5b0ffa9c7f84c?apiKey=023108a9c99043f18acff792c7e6bb89&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets/TEMP/6839c253354f236fbfcf67fd275938cc748419b6ee20ad5356d5b0ffa9c7f84c?apiKey=023108a9c99043f18acff792c7e6bb89&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets/TEMP/6839c253354f236fbfcf67fd275938cc748419b6ee20ad5356d5b0ffa9c7f84c?apiKey=023108a9c99043f18acff792c7e6bb89"
                    class="aspect-[0.99] w-[95px]" />
                </div>
              </div>
              <div class="flex flex-col justify-center p-2.5 mt-5 rounded-lg bg-zinc-50 max-md:max-w-full">
                <div class="flex gap-5 justify-between px-px max-md:flex-wrap max-md:max-w-full">
                  <div class="flex flex-col self-start">
                    <div class="text-lg leading-5 text-center text-blue-600">
                      Nature Photographer
                    </div>
                    <div class="flex gap-1 justify-between mt-2.5 text-sm leading-5 text-stone-500">
                      <div class="my-auto w-3 h-3 bg-lime-600 rounded-full"></div>
                      <div class="flex-auto">45 freelancer</div>
                    </div>
                    <img loading="lazy"
                      srcSet="https://cdn.builder.io/api/v1/image/assets/TEMP/cfecbe0181c315cca64f27d89122240993d02d0aca3eb156d3405b8a102727fc?apiKey=023108a9c99043f18acff792c7e6bb89&width=100 100w, https://cdn.builder.io/api/v1/image/assets/TEMP/cfecbe0181c315cca64f27d89122240993d02d0aca3eb156d3405b8a102727fc?apiKey=023108a9c99043f18acff792c7e6bb89&width=200 200w, https://cdn.builder.io/api/v1/image/assets/TEMP/cfecbe0181c315cca64f27d89122240993d02d0aca3eb156d3405b8a102727fc?apiKey=023108a9c99043f18acff792c7e6bb89&width=400 400w, https://cdn.builder.io/api/v1/image/assets/TEMP/cfecbe0181c315cca64f27d89122240993d02d0aca3eb156d3405b8a102727fc?apiKey=023108a9c99043f18acff792c7e6bb89&width=800 800w, https://cdn.builder.io/api/v1/image/assets/TEMP/cfecbe0181c315cca64f27d89122240993d02d0aca3eb156d3405b8a102727fc?apiKey=023108a9c99043f18acff792c7e6bb89&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets/TEMP/cfecbe0181c315cca64f27d89122240993d02d0aca3eb156d3405b8a102727fc?apiKey=023108a9c99043f18acff792c7e6bb89&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets/TEMP/cfecbe0181c315cca64f27d89122240993d02d0aca3eb156d3405b8a102727fc?apiKey=023108a9c99043f18acff792c7e6bb89&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets/TEMP/cfecbe0181c315cca64f27d89122240993d02d0aca3eb156d3405b8a102727fc?apiKey=023108a9c99043f18acff792c7e6bb89"
                      class="mt-2.5 max-w-full aspect-[3.23] w-[116px]" />
                  </div>
                  <img loading="lazy"
                    srcSet="https://cdn.builder.io/api/v1/image/assets/TEMP/fab34790ad2a9a59d169be0cb8de48cee685211e3fedc707dd5d357643122b85?apiKey=023108a9c99043f18acff792c7e6bb89&width=100 100w, https://cdn.builder.io/api/v1/image/assets/TEMP/fab34790ad2a9a59d169be0cb8de48cee685211e3fedc707dd5d357643122b85?apiKey=023108a9c99043f18acff792c7e6bb89&width=200 200w, https://cdn.builder.io/api/v1/image/assets/TEMP/fab34790ad2a9a59d169be0cb8de48cee685211e3fedc707dd5d357643122b85?apiKey=023108a9c99043f18acff792c7e6bb89&width=400 400w, https://cdn.builder.io/api/v1/image/assets/TEMP/fab34790ad2a9a59d169be0cb8de48cee685211e3fedc707dd5d357643122b85?apiKey=023108a9c99043f18acff792c7e6bb89&width=800 800w, https://cdn.builder.io/api/v1/image/assets/TEMP/fab34790ad2a9a59d169be0cb8de48cee685211e3fedc707dd5d357643122b85?apiKey=023108a9c99043f18acff792c7e6bb89&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets/TEMP/fab34790ad2a9a59d169be0cb8de48cee685211e3fedc707dd5d357643122b85?apiKey=023108a9c99043f18acff792c7e6bb89&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets/TEMP/fab34790ad2a9a59d169be0cb8de48cee685211e3fedc707dd5d357643122b85?apiKey=023108a9c99043f18acff792c7e6bb89&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets/TEMP/fab34790ad2a9a59d169be0cb8de48cee685211e3fedc707dd5d357643122b85?apiKey=023108a9c99043f18acff792c7e6bb89"
                    class="aspect-square w-[95px]" />
                </div>
              </div>
              <div class="flex flex-col justify-center p-2.5 mt-5 rounded-lg bg-zinc-50 max-md:max-w-full">
                <div class="flex gap-5 justify-between px-px max-md:flex-wrap max-md:max-w-full">
                  <div class="flex flex-col self-start">
                    <div class="text-lg leading-5 text-center text-blue-600">
                      Micro Photographer
                    </div>
                    <div class="flex gap-1 justify-between mt-2.5 text-sm leading-5 text-stone-500">
                      <div class="my-auto w-3 h-3 bg-lime-600 rounded-full"></div>
                      <div class="flex-auto">45 freelancer</div>
                    </div>
                    <img loading="lazy"
                      srcSet="https://cdn.builder.io/api/v1/image/assets/TEMP/1fb340996da9f299f9233acfb501c251782fcac71bd39e51b1cb3f9384b66688?apiKey=023108a9c99043f18acff792c7e6bb89&width=100 100w, https://cdn.builder.io/api/v1/image/assets/TEMP/1fb340996da9f299f9233acfb501c251782fcac71bd39e51b1cb3f9384b66688?apiKey=023108a9c99043f18acff792c7e6bb89&width=200 200w, https://cdn.builder.io/api/v1/image/assets/TEMP/1fb340996da9f299f9233acfb501c251782fcac71bd39e51b1cb3f9384b66688?apiKey=023108a9c99043f18acff792c7e6bb89&width=400 400w, https://cdn.builder.io/api/v1/image/assets/TEMP/1fb340996da9f299f9233acfb501c251782fcac71bd39e51b1cb3f9384b66688?apiKey=023108a9c99043f18acff792c7e6bb89&width=800 800w, https://cdn.builder.io/api/v1/image/assets/TEMP/1fb340996da9f299f9233acfb501c251782fcac71bd39e51b1cb3f9384b66688?apiKey=023108a9c99043f18acff792c7e6bb89&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets/TEMP/1fb340996da9f299f9233acfb501c251782fcac71bd39e51b1cb3f9384b66688?apiKey=023108a9c99043f18acff792c7e6bb89&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets/TEMP/1fb340996da9f299f9233acfb501c251782fcac71bd39e51b1cb3f9384b66688?apiKey=023108a9c99043f18acff792c7e6bb89&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets/TEMP/1fb340996da9f299f9233acfb501c251782fcac71bd39e51b1cb3f9384b66688?apiKey=023108a9c99043f18acff792c7e6bb89"
                      class="mt-2.5 max-w-full aspect-[3.23] w-[116px]" />
                  </div>
                  <img loading="lazy"
                    srcSet="https://cdn.builder.io/api/v1/image/assets/TEMP/6839c253354f236fbfcf67fd275938cc748419b6ee20ad5356d5b0ffa9c7f84c?apiKey=023108a9c99043f18acff792c7e6bb89&width=100 100w, https://cdn.builder.io/api/v1/image/assets/TEMP/6839c253354f236fbfcf67fd275938cc748419b6ee20ad5356d5b0ffa9c7f84c?apiKey=023108a9c99043f18acff792c7e6bb89&width=200 200w, https://cdn.builder.io/api/v1/image/assets/TEMP/6839c253354f236fbfcf67fd275938cc748419b6ee20ad5356d5b0ffa9c7f84c?apiKey=023108a9c99043f18acff792c7e6bb89&width=400 400w, https://cdn.builder.io/api/v1/image/assets/TEMP/6839c253354f236fbfcf67fd275938cc748419b6ee20ad5356d5b0ffa9c7f84c?apiKey=023108a9c99043f18acff792c7e6bb89&width=800 800w, https://cdn.builder.io/api/v1/image/assets/TEMP/6839c253354f236fbfcf67fd275938cc748419b6ee20ad5356d5b0ffa9c7f84c?apiKey=023108a9c99043f18acff792c7e6bb89&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets/TEMP/6839c253354f236fbfcf67fd275938cc748419b6ee20ad5356d5b0ffa9c7f84c?apiKey=023108a9c99043f18acff792c7e6bb89&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets/TEMP/6839c253354f236fbfcf67fd275938cc748419b6ee20ad5356d5b0ffa9c7f84c?apiKey=023108a9c99043f18acff792c7e6bb89&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets/TEMP/6839c253354f236fbfcf67fd275938cc748419b6ee20ad5356d5b0ffa9c7f84c?apiKey=023108a9c99043f18acff792c7e6bb89"
                    class="aspect-[0.99] w-[95px]" />
                </div>
              </div>
              <div class="flex flex-col justify-center p-2.5 mt-5 rounded-lg bg-zinc-50 max-md:max-w-full">
                <div class="flex gap-5 justify-between px-px max-md:flex-wrap max-md:max-w-full">
                  <div class="flex flex-col self-start">
                    <div class="text-lg leading-5 text-center text-blue-600">
                      Group Photographer
                    </div>
                    <div class="flex gap-1 justify-between mt-2.5 text-sm leading-5 text-stone-500">
                      <div class="my-auto w-3 h-3 bg-lime-600 rounded-full"></div>
                      <div class="flex-auto">45 freelancer</div>
                    </div>
                    <img loading="lazy"
                      srcSet="https://cdn.builder.io/api/v1/image/assets/TEMP/cfecbe0181c315cca64f27d89122240993d02d0aca3eb156d3405b8a102727fc?apiKey=023108a9c99043f18acff792c7e6bb89&width=100 100w, https://cdn.builder.io/api/v1/image/assets/TEMP/cfecbe0181c315cca64f27d89122240993d02d0aca3eb156d3405b8a102727fc?apiKey=023108a9c99043f18acff792c7e6bb89&width=200 200w, https://cdn.builder.io/api/v1/image/assets/TEMP/cfecbe0181c315cca64f27d89122240993d02d0aca3eb156d3405b8a102727fc?apiKey=023108a9c99043f18acff792c7e6bb89&width=400 400w, https://cdn.builder.io/api/v1/image/assets/TEMP/cfecbe0181c315cca64f27d89122240993d02d0aca3eb156d3405b8a102727fc?apiKey=023108a9c99043f18acff792c7e6bb89&width=800 800w, https://cdn.builder.io/api/v1/image/assets/TEMP/cfecbe0181c315cca64f27d89122240993d02d0aca3eb156d3405b8a102727fc?apiKey=023108a9c99043f18acff792c7e6bb89&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets/TEMP/cfecbe0181c315cca64f27d89122240993d02d0aca3eb156d3405b8a102727fc?apiKey=023108a9c99043f18acff792c7e6bb89&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets/TEMP/cfecbe0181c315cca64f27d89122240993d02d0aca3eb156d3405b8a102727fc?apiKey=023108a9c99043f18acff792c7e6bb89&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets/TEMP/cfecbe0181c315cca64f27d89122240993d02d0aca3eb156d3405b8a102727fc?apiKey=023108a9c99043f18acff792c7e6bb89"
                      class="mt-2.5 max-w-full aspect-[3.23] w-[116px]" />
                  </div>
                  <img loading="lazy"
                    srcSet="https://cdn.builder.io/api/v1/image/assets/TEMP/fab34790ad2a9a59d169be0cb8de48cee685211e3fedc707dd5d357643122b85?apiKey=023108a9c99043f18acff792c7e6bb89&width=100 100w, https://cdn.builder.io/api/v1/image/assets/TEMP/fab34790ad2a9a59d169be0cb8de48cee685211e3fedc707dd5d357643122b85?apiKey=023108a9c99043f18acff792c7e6bb89&width=200 200w, https://cdn.builder.io/api/v1/image/assets/TEMP/fab34790ad2a9a59d169be0cb8de48cee685211e3fedc707dd5d357643122b85?apiKey=023108a9c99043f18acff792c7e6bb89&width=400 400w, https://cdn.builder.io/api/v1/image/assets/TEMP/fab34790ad2a9a59d169be0cb8de48cee685211e3fedc707dd5d357643122b85?apiKey=023108a9c99043f18acff792c7e6bb89&width=800 800w, https://cdn.builder.io/api/v1/image/assets/TEMP/fab34790ad2a9a59d169be0cb8de48cee685211e3fedc707dd5d357643122b85?apiKey=023108a9c99043f18acff792c7e6bb89&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets/TEMP/fab34790ad2a9a59d169be0cb8de48cee685211e3fedc707dd5d357643122b85?apiKey=023108a9c99043f18acff792c7e6bb89&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets/TEMP/fab34790ad2a9a59d169be0cb8de48cee685211e3fedc707dd5d357643122b85?apiKey=023108a9c99043f18acff792c7e6bb89&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets/TEMP/fab34790ad2a9a59d169be0cb8de48cee685211e3fedc707dd5d357643122b85?apiKey=023108a9c99043f18acff792c7e6bb89"
                    class="aspect-square w-[95px]" />
                </div>
              </div>
              <div class="flex flex-col justify-center p-2.5 mt-5 rounded-lg bg-zinc-50 max-md:max-w-full">
                <div class="flex gap-5 justify-between px-px max-md:flex-wrap max-md:max-w-full">
                  <div class="flex flex-col self-start">
                    <div class="text-lg leading-5 text-center text-blue-600">
                      Nature Photographer
                    </div>
                    <div class="flex gap-1 justify-between mt-2.5 text-sm leading-5 text-stone-500">
                      <div class="my-auto w-3 h-3 bg-lime-600 rounded-full"></div>
                      <div class="flex-auto">45 freelancer</div>
                    </div>
                    <img loading="lazy"
                      srcSet="https://cdn.builder.io/api/v1/image/assets/TEMP/1fb340996da9f299f9233acfb501c251782fcac71bd39e51b1cb3f9384b66688?apiKey=023108a9c99043f18acff792c7e6bb89&width=100 100w, https://cdn.builder.io/api/v1/image/assets/TEMP/1fb340996da9f299f9233acfb501c251782fcac71bd39e51b1cb3f9384b66688?apiKey=023108a9c99043f18acff792c7e6bb89&width=200 200w, https://cdn.builder.io/api/v1/image/assets/TEMP/1fb340996da9f299f9233acfb501c251782fcac71bd39e51b1cb3f9384b66688?apiKey=023108a9c99043f18acff792c7e6bb89&width=400 400w, https://cdn.builder.io/api/v1/image/assets/TEMP/1fb340996da9f299f9233acfb501c251782fcac71bd39e51b1cb3f9384b66688?apiKey=023108a9c99043f18acff792c7e6bb89&width=800 800w, https://cdn.builder.io/api/v1/image/assets/TEMP/1fb340996da9f299f9233acfb501c251782fcac71bd39e51b1cb3f9384b66688?apiKey=023108a9c99043f18acff792c7e6bb89&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets/TEMP/1fb340996da9f299f9233acfb501c251782fcac71bd39e51b1cb3f9384b66688?apiKey=023108a9c99043f18acff792c7e6bb89&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets/TEMP/1fb340996da9f299f9233acfb501c251782fcac71bd39e51b1cb3f9384b66688?apiKey=023108a9c99043f18acff792c7e6bb89&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets/TEMP/1fb340996da9f299f9233acfb501c251782fcac71bd39e51b1cb3f9384b66688?apiKey=023108a9c99043f18acff792c7e6bb89"
                      class="mt-2.5 max-w-full aspect-[3.23] w-[116px]" />
                  </div>
                  <img loading="lazy"
                    srcSet="https://cdn.builder.io/api/v1/image/assets/TEMP/6839c253354f236fbfcf67fd275938cc748419b6ee20ad5356d5b0ffa9c7f84c?apiKey=023108a9c99043f18acff792c7e6bb89&width=100 100w, https://cdn.builder.io/api/v1/image/assets/TEMP/6839c253354f236fbfcf67fd275938cc748419b6ee20ad5356d5b0ffa9c7f84c?apiKey=023108a9c99043f18acff792c7e6bb89&width=200 200w, https://cdn.builder.io/api/v1/image/assets/TEMP/6839c253354f236fbfcf67fd275938cc748419b6ee20ad5356d5b0ffa9c7f84c?apiKey=023108a9c99043f18acff792c7e6bb89&width=400 400w, https://cdn.builder.io/api/v1/image/assets/TEMP/6839c253354f236fbfcf67fd275938cc748419b6ee20ad5356d5b0ffa9c7f84c?apiKey=023108a9c99043f18acff792c7e6bb89&width=800 800w, https://cdn.builder.io/api/v1/image/assets/TEMP/6839c253354f236fbfcf67fd275938cc748419b6ee20ad5356d5b0ffa9c7f84c?apiKey=023108a9c99043f18acff792c7e6bb89&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets/TEMP/6839c253354f236fbfcf67fd275938cc748419b6ee20ad5356d5b0ffa9c7f84c?apiKey=023108a9c99043f18acff792c7e6bb89&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets/TEMP/6839c253354f236fbfcf67fd275938cc748419b6ee20ad5356d5b0ffa9c7f84c?apiKey=023108a9c99043f18acff792c7e6bb89&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets/TEMP/6839c253354f236fbfcf67fd275938cc748419b6ee20ad5356d5b0ffa9c7f84c?apiKey=023108a9c99043f18acff792c7e6bb89"
                    class="aspect-[0.99] w-[95px]" />
                </div>
              </div>
            </div>
          </div>
          <div class="flex flex-col ml-5 w-[57%] max-md:ml-0 max-md:w-full">
            <div
              class="flex overflow-hidden relative flex-col items-start self-stretch px-20 pt-8 pb-1.5 my-auto min-h-[671px] max-md:px-5 max-md:mt-10 max-md:max-w-full">
              <img loading="lazy"
                srcSet="https://cdn.builder.io/api/v1/image/assets/TEMP/03066f6f800bc8c36fc40957a8c5ff173908bb17169c045dce18d36537b4b049?apiKey=023108a9c99043f18acff792c7e6bb89&width=100 100w, https://cdn.builder.io/api/v1/image/assets/TEMP/03066f6f800bc8c36fc40957a8c5ff173908bb17169c045dce18d36537b4b049?apiKey=023108a9c99043f18acff792c7e6bb89&width=200 200w, https://cdn.builder.io/api/v1/image/assets/TEMP/03066f6f800bc8c36fc40957a8c5ff173908bb17169c045dce18d36537b4b049?apiKey=023108a9c99043f18acff792c7e6bb89&width=400 400w, https://cdn.builder.io/api/v1/image/assets/TEMP/03066f6f800bc8c36fc40957a8c5ff173908bb17169c045dce18d36537b4b049?apiKey=023108a9c99043f18acff792c7e6bb89&width=800 800w, https://cdn.builder.io/api/v1/image/assets/TEMP/03066f6f800bc8c36fc40957a8c5ff173908bb17169c045dce18d36537b4b049?apiKey=023108a9c99043f18acff792c7e6bb89&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets/TEMP/03066f6f800bc8c36fc40957a8c5ff173908bb17169c045dce18d36537b4b049?apiKey=023108a9c99043f18acff792c7e6bb89&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets/TEMP/03066f6f800bc8c36fc40957a8c5ff173908bb17169c045dce18d36537b4b049?apiKey=023108a9c99043f18acff792c7e6bb89&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets/TEMP/03066f6f800bc8c36fc40957a8c5ff173908bb17169c045dce18d36537b4b049?apiKey=023108a9c99043f18acff792c7e6bb89"
                class="object-cover absolute inset-0 size-full" />
              <div class="flex relative flex-col max-w-full w-[498px]">
                <img loading="lazy"
                  srcSet="https://cdn.builder.io/api/v1/image/assets/TEMP/19c1b691da412a5b3cfc3f312bc587946c604f6295790b3f3b64342e750f665e?apiKey=023108a9c99043f18acff792c7e6bb89&width=100 100w, https://cdn.builder.io/api/v1/image/assets/TEMP/19c1b691da412a5b3cfc3f312bc587946c604f6295790b3f3b64342e750f665e?apiKey=023108a9c99043f18acff792c7e6bb89&width=200 200w, https://cdn.builder.io/api/v1/image/assets/TEMP/19c1b691da412a5b3cfc3f312bc587946c604f6295790b3f3b64342e750f665e?apiKey=023108a9c99043f18acff792c7e6bb89&width=400 400w, https://cdn.builder.io/api/v1/image/assets/TEMP/19c1b691da412a5b3cfc3f312bc587946c604f6295790b3f3b64342e750f665e?apiKey=023108a9c99043f18acff792c7e6bb89&width=800 800w, https://cdn.builder.io/api/v1/image/assets/TEMP/19c1b691da412a5b3cfc3f312bc587946c604f6295790b3f3b64342e750f665e?apiKey=023108a9c99043f18acff792c7e6bb89&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets/TEMP/19c1b691da412a5b3cfc3f312bc587946c604f6295790b3f3b64342e750f665e?apiKey=023108a9c99043f18acff792c7e6bb89&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets/TEMP/19c1b691da412a5b3cfc3f312bc587946c604f6295790b3f3b64342e750f665e?apiKey=023108a9c99043f18acff792c7e6bb89&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets/TEMP/19c1b691da412a5b3cfc3f312bc587946c604f6295790b3f3b64342e750f665e?apiKey=023108a9c99043f18acff792c7e6bb89"
                  class="ml-9 aspect-[0.61] w-[51px] max-md:ml-2.5" /><img loading="lazy"
                  srcSet="https://cdn.builder.io/api/v1/image/assets/TEMP/2e67db177b6b8c57a36a2e217020ff90d8bba8c0f45e7eadb347c0d443260d5d?apiKey=023108a9c99043f18acff792c7e6bb89&width=100 100w, https://cdn.builder.io/api/v1/image/assets/TEMP/2e67db177b6b8c57a36a2e217020ff90d8bba8c0f45e7eadb347c0d443260d5d?apiKey=023108a9c99043f18acff792c7e6bb89&width=200 200w, https://cdn.builder.io/api/v1/image/assets/TEMP/2e67db177b6b8c57a36a2e217020ff90d8bba8c0f45e7eadb347c0d443260d5d?apiKey=023108a9c99043f18acff792c7e6bb89&width=400 400w, https://cdn.builder.io/api/v1/image/assets/TEMP/2e67db177b6b8c57a36a2e217020ff90d8bba8c0f45e7eadb347c0d443260d5d?apiKey=023108a9c99043f18acff792c7e6bb89&width=800 800w, https://cdn.builder.io/api/v1/image/assets/TEMP/2e67db177b6b8c57a36a2e217020ff90d8bba8c0f45e7eadb347c0d443260d5d?apiKey=023108a9c99043f18acff792c7e6bb89&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets/TEMP/2e67db177b6b8c57a36a2e217020ff90d8bba8c0f45e7eadb347c0d443260d5d?apiKey=023108a9c99043f18acff792c7e6bb89&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets/TEMP/2e67db177b6b8c57a36a2e217020ff90d8bba8c0f45e7eadb347c0d443260d5d?apiKey=023108a9c99043f18acff792c7e6bb89&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets/TEMP/2e67db177b6b8c57a36a2e217020ff90d8bba8c0f45e7eadb347c0d443260d5d?apiKey=023108a9c99043f18acff792c7e6bb89"
                  class="mt-14 aspect-[0.61] w-[51px] max-md:mt-10" /><img loading="lazy"
                  srcSet="https://cdn.builder.io/api/v1/image/assets/TEMP/85c93e5e52799dc5912ec30118c52dc6897b26eaaea50c87af1f9870e8da9c82?apiKey=023108a9c99043f18acff792c7e6bb89&width=100 100w, https://cdn.builder.io/api/v1/image/assets/TEMP/85c93e5e52799dc5912ec30118c52dc6897b26eaaea50c87af1f9870e8da9c82?apiKey=023108a9c99043f18acff792c7e6bb89&width=200 200w, https://cdn.builder.io/api/v1/image/assets/TEMP/85c93e5e52799dc5912ec30118c52dc6897b26eaaea50c87af1f9870e8da9c82?apiKey=023108a9c99043f18acff792c7e6bb89&width=400 400w, https://cdn.builder.io/api/v1/image/assets/TEMP/85c93e5e52799dc5912ec30118c52dc6897b26eaaea50c87af1f9870e8da9c82?apiKey=023108a9c99043f18acff792c7e6bb89&width=800 800w, https://cdn.builder.io/api/v1/image/assets/TEMP/85c93e5e52799dc5912ec30118c52dc6897b26eaaea50c87af1f9870e8da9c82?apiKey=023108a9c99043f18acff792c7e6bb89&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets/TEMP/85c93e5e52799dc5912ec30118c52dc6897b26eaaea50c87af1f9870e8da9c82?apiKey=023108a9c99043f18acff792c7e6bb89&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets/TEMP/85c93e5e52799dc5912ec30118c52dc6897b26eaaea50c87af1f9870e8da9c82?apiKey=023108a9c99043f18acff792c7e6bb89&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets/TEMP/85c93e5e52799dc5912ec30118c52dc6897b26eaaea50c87af1f9870e8da9c82?apiKey=023108a9c99043f18acff792c7e6bb89"
                  class="self-end mt-1.5 mr-8 aspect-[0.61] w-[51px] max-md:mr-2.5" /><img loading="lazy"
                  srcSet="https://cdn.builder.io/api/v1/image/assets/TEMP/46737e962f31a8d104f9695fed6891f38c7f5b212876a4e0e87b9182e2966ecb?apiKey=023108a9c99043f18acff792c7e6bb89&width=100 100w, https://cdn.builder.io/api/v1/image/assets/TEMP/46737e962f31a8d104f9695fed6891f38c7f5b212876a4e0e87b9182e2966ecb?apiKey=023108a9c99043f18acff792c7e6bb89&width=200 200w, https://cdn.builder.io/api/v1/image/assets/TEMP/46737e962f31a8d104f9695fed6891f38c7f5b212876a4e0e87b9182e2966ecb?apiKey=023108a9c99043f18acff792c7e6bb89&width=400 400w, https://cdn.builder.io/api/v1/image/assets/TEMP/46737e962f31a8d104f9695fed6891f38c7f5b212876a4e0e87b9182e2966ecb?apiKey=023108a9c99043f18acff792c7e6bb89&width=800 800w, https://cdn.builder.io/api/v1/image/assets/TEMP/46737e962f31a8d104f9695fed6891f38c7f5b212876a4e0e87b9182e2966ecb?apiKey=023108a9c99043f18acff792c7e6bb89&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets/TEMP/46737e962f31a8d104f9695fed6891f38c7f5b212876a4e0e87b9182e2966ecb?apiKey=023108a9c99043f18acff792c7e6bb89&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets/TEMP/46737e962f31a8d104f9695fed6891f38c7f5b212876a4e0e87b9182e2966ecb?apiKey=023108a9c99043f18acff792c7e6bb89&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets/TEMP/46737e962f31a8d104f9695fed6891f38c7f5b212876a4e0e87b9182e2966ecb?apiKey=023108a9c99043f18acff792c7e6bb89"
                  class="self-end mt-16 aspect-[0.61] w-[51px] max-md:mt-10" />
              </div>
              <div
                class="flex relative gap-5 justify-between items-start mt-11 ml-6 max-w-full w-[352px] max-md:mt-10 max-md:ml-2.5">
                <img loading="lazy"
                  srcSet="https://cdn.builder.io/api/v1/image/assets/TEMP/10ca5d563fefa321b70356f44e5abf65b028025db60ad06eeb46d22aadf6844f?apiKey=023108a9c99043f18acff792c7e6bb89&width=100 100w, https://cdn.builder.io/api/v1/image/assets/TEMP/10ca5d563fefa321b70356f44e5abf65b028025db60ad06eeb46d22aadf6844f?apiKey=023108a9c99043f18acff792c7e6bb89&width=200 200w, https://cdn.builder.io/api/v1/image/assets/TEMP/10ca5d563fefa321b70356f44e5abf65b028025db60ad06eeb46d22aadf6844f?apiKey=023108a9c99043f18acff792c7e6bb89&width=400 400w, https://cdn.builder.io/api/v1/image/assets/TEMP/10ca5d563fefa321b70356f44e5abf65b028025db60ad06eeb46d22aadf6844f?apiKey=023108a9c99043f18acff792c7e6bb89&width=800 800w, https://cdn.builder.io/api/v1/image/assets/TEMP/10ca5d563fefa321b70356f44e5abf65b028025db60ad06eeb46d22aadf6844f?apiKey=023108a9c99043f18acff792c7e6bb89&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets/TEMP/10ca5d563fefa321b70356f44e5abf65b028025db60ad06eeb46d22aadf6844f?apiKey=023108a9c99043f18acff792c7e6bb89&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets/TEMP/10ca5d563fefa321b70356f44e5abf65b028025db60ad06eeb46d22aadf6844f?apiKey=023108a9c99043f18acff792c7e6bb89&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets/TEMP/10ca5d563fefa321b70356f44e5abf65b028025db60ad06eeb46d22aadf6844f?apiKey=023108a9c99043f18acff792c7e6bb89"
                  class="flex-1 shrink-0 w-full aspect-[0.61]" /><img loading="lazy"
                  srcSet="https://cdn.builder.io/api/v1/image/assets/TEMP/38f2f702539365491ddacb16bdac168fae2a25bb1a18aae890a565d85ef15d7f?apiKey=023108a9c99043f18acff792c7e6bb89&width=100 100w, https://cdn.builder.io/api/v1/image/assets/TEMP/38f2f702539365491ddacb16bdac168fae2a25bb1a18aae890a565d85ef15d7f?apiKey=023108a9c99043f18acff792c7e6bb89&width=200 200w, https://cdn.builder.io/api/v1/image/assets/TEMP/38f2f702539365491ddacb16bdac168fae2a25bb1a18aae890a565d85ef15d7f?apiKey=023108a9c99043f18acff792c7e6bb89&width=400 400w, https://cdn.builder.io/api/v1/image/assets/TEMP/38f2f702539365491ddacb16bdac168fae2a25bb1a18aae890a565d85ef15d7f?apiKey=023108a9c99043f18acff792c7e6bb89&width=800 800w, https://cdn.builder.io/api/v1/image/assets/TEMP/38f2f702539365491ddacb16bdac168fae2a25bb1a18aae890a565d85ef15d7f?apiKey=023108a9c99043f18acff792c7e6bb89&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets/TEMP/38f2f702539365491ddacb16bdac168fae2a25bb1a18aae890a565d85ef15d7f?apiKey=023108a9c99043f18acff792c7e6bb89&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets/TEMP/38f2f702539365491ddacb16bdac168fae2a25bb1a18aae890a565d85ef15d7f?apiKey=023108a9c99043f18acff792c7e6bb89&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets/TEMP/38f2f702539365491ddacb16bdac168fae2a25bb1a18aae890a565d85ef15d7f?apiKey=023108a9c99043f18acff792c7e6bb89"
                  class="flex-1 shrink-0 mt-12 w-full aspect-[0.61] max-md:mt-10" />
              </div>
            </div>
          </div>
        </div>
      </div>
      <div
        class="flex flex-col items-center px-16 pt-7 pb-4 w-full text-lg font-bold leading-5 text-center whitespace-nowrap text-white text-opacity-90 max-md:px-5 max-md:max-w-full">
        <div class="justify-center px-9 py-5 bg-blue-600 shadow-sm rounded-[30px] max-md:px-5">
          View more
        </div>
      </div>
    </div>
    <div
      class="flex flex-col self-stretch px-20 pt-8 pb-12 mt-12 w-full text-lg leading-7 bg-white text-neutral-800 max-md:px-5 max-md:mt-10 max-md:max-w-full">
      <div class="self-center text-4xl font-medium leading-10 text-zinc-900">
        Category
      </div>
      <div class="self-center mt-3 max-md:max-w-full">
        Learn from Industry Experts and Enhance Your Skills.
      </div>
      <div
        class="flex gap-5 justify-between mt-12 mr-5 ml-4 text-center whitespace-nowrap max-md:flex-wrap max-md:mt-10 max-md:mr-2.5 max-md:max-w-full">
        <div class="flex flex-col flex-1 px-4 py-9 bg-violet-50 rounded-2xl">
          <img loading="lazy"
            srcSet="https://cdn.builder.io/api/v1/image/assets/TEMP/d95170217409c3561ad08e4b45c87a84f4c6357ccae4dcd330c47b356dcb1fea?apiKey=023108a9c99043f18acff792c7e6bb89&width=100 100w, https://cdn.builder.io/api/v1/image/assets/TEMP/d95170217409c3561ad08e4b45c87a84f4c6357ccae4dcd330c47b356dcb1fea?apiKey=023108a9c99043f18acff792c7e6bb89&width=200 200w, https://cdn.builder.io/api/v1/image/assets/TEMP/d95170217409c3561ad08e4b45c87a84f4c6357ccae4dcd330c47b356dcb1fea?apiKey=023108a9c99043f18acff792c7e6bb89&width=400 400w, https://cdn.builder.io/api/v1/image/assets/TEMP/d95170217409c3561ad08e4b45c87a84f4c6357ccae4dcd330c47b356dcb1fea?apiKey=023108a9c99043f18acff792c7e6bb89&width=800 800w, https://cdn.builder.io/api/v1/image/assets/TEMP/d95170217409c3561ad08e4b45c87a84f4c6357ccae4dcd330c47b356dcb1fea?apiKey=023108a9c99043f18acff792c7e6bb89&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets/TEMP/d95170217409c3561ad08e4b45c87a84f4c6357ccae4dcd330c47b356dcb1fea?apiKey=023108a9c99043f18acff792c7e6bb89&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets/TEMP/d95170217409c3561ad08e4b45c87a84f4c6357ccae4dcd330c47b356dcb1fea?apiKey=023108a9c99043f18acff792c7e6bb89&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets/TEMP/d95170217409c3561ad08e4b45c87a84f4c6357ccae4dcd330c47b356dcb1fea?apiKey=023108a9c99043f18acff792c7e6bb89"
            class="self-center aspect-square w-[90px]" />
          <div class="mt-3">Wardrobe</div>
        </div>
        <div class="flex flex-col flex-1 px-4 py-9 bg-violet-50 rounded-2xl">
          <img loading="lazy"
            srcSet="https://cdn.builder.io/api/v1/image/assets/TEMP/a5469a5b49f9c875556feced386eaccd703ea5605f03fa915eefeac0fb8d5f34?apiKey=023108a9c99043f18acff792c7e6bb89&width=100 100w, https://cdn.builder.io/api/v1/image/assets/TEMP/a5469a5b49f9c875556feced386eaccd703ea5605f03fa915eefeac0fb8d5f34?apiKey=023108a9c99043f18acff792c7e6bb89&width=200 200w, https://cdn.builder.io/api/v1/image/assets/TEMP/a5469a5b49f9c875556feced386eaccd703ea5605f03fa915eefeac0fb8d5f34?apiKey=023108a9c99043f18acff792c7e6bb89&width=400 400w, https://cdn.builder.io/api/v1/image/assets/TEMP/a5469a5b49f9c875556feced386eaccd703ea5605f03fa915eefeac0fb8d5f34?apiKey=023108a9c99043f18acff792c7e6bb89&width=800 800w, https://cdn.builder.io/api/v1/image/assets/TEMP/a5469a5b49f9c875556feced386eaccd703ea5605f03fa915eefeac0fb8d5f34?apiKey=023108a9c99043f18acff792c7e6bb89&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets/TEMP/a5469a5b49f9c875556feced386eaccd703ea5605f03fa915eefeac0fb8d5f34?apiKey=023108a9c99043f18acff792c7e6bb89&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets/TEMP/a5469a5b49f9c875556feced386eaccd703ea5605f03fa915eefeac0fb8d5f34?apiKey=023108a9c99043f18acff792c7e6bb89&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets/TEMP/a5469a5b49f9c875556feced386eaccd703ea5605f03fa915eefeac0fb8d5f34?apiKey=023108a9c99043f18acff792c7e6bb89"
            class="self-center aspect-square w-[90px]" />
          <div class="mt-3">Clothier</div>
        </div>
        <div class="flex flex-col flex-1 px-4 py-9 bg-violet-50 rounded-2xl shadow-sm">
          <img loading="lazy"
            srcSet="https://cdn.builder.io/api/v1/image/assets/TEMP/cc88c0419aff170c822fe9a70d5845efe59d9594ab587d62098b016e550b01d9?apiKey=023108a9c99043f18acff792c7e6bb89&width=100 100w, https://cdn.builder.io/api/v1/image/assets/TEMP/cc88c0419aff170c822fe9a70d5845efe59d9594ab587d62098b016e550b01d9?apiKey=023108a9c99043f18acff792c7e6bb89&width=200 200w, https://cdn.builder.io/api/v1/image/assets/TEMP/cc88c0419aff170c822fe9a70d5845efe59d9594ab587d62098b016e550b01d9?apiKey=023108a9c99043f18acff792c7e6bb89&width=400 400w, https://cdn.builder.io/api/v1/image/assets/TEMP/cc88c0419aff170c822fe9a70d5845efe59d9594ab587d62098b016e550b01d9?apiKey=023108a9c99043f18acff792c7e6bb89&width=800 800w, https://cdn.builder.io/api/v1/image/assets/TEMP/cc88c0419aff170c822fe9a70d5845efe59d9594ab587d62098b016e550b01d9?apiKey=023108a9c99043f18acff792c7e6bb89&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets/TEMP/cc88c0419aff170c822fe9a70d5845efe59d9594ab587d62098b016e550b01d9?apiKey=023108a9c99043f18acff792c7e6bb89&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets/TEMP/cc88c0419aff170c822fe9a70d5845efe59d9594ab587d62098b016e550b01d9?apiKey=023108a9c99043f18acff792c7e6bb89&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets/TEMP/cc88c0419aff170c822fe9a70d5845efe59d9594ab587d62098b016e550b01d9?apiKey=023108a9c99043f18acff792c7e6bb89"
            class="self-center aspect-square w-[90px]" />
          <div class="mt-3">Personal Stylist</div>
        </div>
        <div class="flex flex-col flex-1 px-4 py-9 bg-violet-50 rounded-2xl">
          <img loading="lazy"
            srcSet="https://cdn.builder.io/api/v1/image/assets/TEMP/0cc1daeae26f93c611aa2fe5afc0545ee8ccaad11ecd12afab57f18c13678491?apiKey=023108a9c99043f18acff792c7e6bb89&width=100 100w, https://cdn.builder.io/api/v1/image/assets/TEMP/0cc1daeae26f93c611aa2fe5afc0545ee8ccaad11ecd12afab57f18c13678491?apiKey=023108a9c99043f18acff792c7e6bb89&width=200 200w, https://cdn.builder.io/api/v1/image/assets/TEMP/0cc1daeae26f93c611aa2fe5afc0545ee8ccaad11ecd12afab57f18c13678491?apiKey=023108a9c99043f18acff792c7e6bb89&width=400 400w, https://cdn.builder.io/api/v1/image/assets/TEMP/0cc1daeae26f93c611aa2fe5afc0545ee8ccaad11ecd12afab57f18c13678491?apiKey=023108a9c99043f18acff792c7e6bb89&width=800 800w, https://cdn.builder.io/api/v1/image/assets/TEMP/0cc1daeae26f93c611aa2fe5afc0545ee8ccaad11ecd12afab57f18c13678491?apiKey=023108a9c99043f18acff792c7e6bb89&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets/TEMP/0cc1daeae26f93c611aa2fe5afc0545ee8ccaad11ecd12afab57f18c13678491?apiKey=023108a9c99043f18acff792c7e6bb89&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets/TEMP/0cc1daeae26f93c611aa2fe5afc0545ee8ccaad11ecd12afab57f18c13678491?apiKey=023108a9c99043f18acff792c7e6bb89&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets/TEMP/0cc1daeae26f93c611aa2fe5afc0545ee8ccaad11ecd12afab57f18c13678491?apiKey=023108a9c99043f18acff792c7e6bb89"
            class="self-center aspect-square w-[90px]" />
          <div class="mt-3">Personal Shopper</div>
        </div>
        <div class="flex flex-col flex-1 px-4 py-9 bg-violet-50 rounded-2xl">
          <img loading="lazy"
            srcSet="https://cdn.builder.io/api/v1/image/assets/TEMP/e8889e6c2dc7335de03190e0760abca7ccd8e20072ad1fe12c6cd77e97c61e9f?apiKey=023108a9c99043f18acff792c7e6bb89&width=100 100w, https://cdn.builder.io/api/v1/image/assets/TEMP/e8889e6c2dc7335de03190e0760abca7ccd8e20072ad1fe12c6cd77e97c61e9f?apiKey=023108a9c99043f18acff792c7e6bb89&width=200 200w, https://cdn.builder.io/api/v1/image/assets/TEMP/e8889e6c2dc7335de03190e0760abca7ccd8e20072ad1fe12c6cd77e97c61e9f?apiKey=023108a9c99043f18acff792c7e6bb89&width=400 400w, https://cdn.builder.io/api/v1/image/assets/TEMP/e8889e6c2dc7335de03190e0760abca7ccd8e20072ad1fe12c6cd77e97c61e9f?apiKey=023108a9c99043f18acff792c7e6bb89&width=800 800w, https://cdn.builder.io/api/v1/image/assets/TEMP/e8889e6c2dc7335de03190e0760abca7ccd8e20072ad1fe12c6cd77e97c61e9f?apiKey=023108a9c99043f18acff792c7e6bb89&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets/TEMP/e8889e6c2dc7335de03190e0760abca7ccd8e20072ad1fe12c6cd77e97c61e9f?apiKey=023108a9c99043f18acff792c7e6bb89&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets/TEMP/e8889e6c2dc7335de03190e0760abca7ccd8e20072ad1fe12c6cd77e97c61e9f?apiKey=023108a9c99043f18acff792c7e6bb89&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets/TEMP/e8889e6c2dc7335de03190e0760abca7ccd8e20072ad1fe12c6cd77e97c61e9f?apiKey=023108a9c99043f18acff792c7e6bb89"
            class="self-center aspect-square w-[90px]" />
          <div class="mt-3">Photographer</div>
        </div>
      </div>
      <div
        class="flex gap-5 justify-between mt-8 mr-5 mb-3.5 ml-4 text-center whitespace-nowrap max-md:flex-wrap max-md:mr-2.5 max-md:max-w-full">
        <div class="flex flex-col flex-1 px-4 py-9 bg-violet-50 rounded-2xl">
          <img loading="lazy"
            srcSet="https://cdn.builder.io/api/v1/image/assets/TEMP/9e94f7b4f9374804010eea5f796119a4419a4bc840e2d7adf8c4fa70dac00497?apiKey=023108a9c99043f18acff792c7e6bb89&width=100 100w, https://cdn.builder.io/api/v1/image/assets/TEMP/9e94f7b4f9374804010eea5f796119a4419a4bc840e2d7adf8c4fa70dac00497?apiKey=023108a9c99043f18acff792c7e6bb89&width=200 200w, https://cdn.builder.io/api/v1/image/assets/TEMP/9e94f7b4f9374804010eea5f796119a4419a4bc840e2d7adf8c4fa70dac00497?apiKey=023108a9c99043f18acff792c7e6bb89&width=400 400w, https://cdn.builder.io/api/v1/image/assets/TEMP/9e94f7b4f9374804010eea5f796119a4419a4bc840e2d7adf8c4fa70dac00497?apiKey=023108a9c99043f18acff792c7e6bb89&width=800 800w, https://cdn.builder.io/api/v1/image/assets/TEMP/9e94f7b4f9374804010eea5f796119a4419a4bc840e2d7adf8c4fa70dac00497?apiKey=023108a9c99043f18acff792c7e6bb89&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets/TEMP/9e94f7b4f9374804010eea5f796119a4419a4bc840e2d7adf8c4fa70dac00497?apiKey=023108a9c99043f18acff792c7e6bb89&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets/TEMP/9e94f7b4f9374804010eea5f796119a4419a4bc840e2d7adf8c4fa70dac00497?apiKey=023108a9c99043f18acff792c7e6bb89&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets/TEMP/9e94f7b4f9374804010eea5f796119a4419a4bc840e2d7adf8c4fa70dac00497?apiKey=023108a9c99043f18acff792c7e6bb89"
            class="self-center aspect-square w-[90px]" />
          <div class="mt-3">Family Photography</div>
        </div>
        <div class="flex flex-col flex-1 px-4 py-9 bg-violet-50 rounded-2xl">
          <img loading="lazy"
            srcSet="https://cdn.builder.io/api/v1/image/assets/TEMP/a6cb7f621cafd1e2da38f70b4566f0a74032c40ba318ab3a7818fa04b067bef3?apiKey=023108a9c99043f18acff792c7e6bb89&width=100 100w, https://cdn.builder.io/api/v1/image/assets/TEMP/a6cb7f621cafd1e2da38f70b4566f0a74032c40ba318ab3a7818fa04b067bef3?apiKey=023108a9c99043f18acff792c7e6bb89&width=200 200w, https://cdn.builder.io/api/v1/image/assets/TEMP/a6cb7f621cafd1e2da38f70b4566f0a74032c40ba318ab3a7818fa04b067bef3?apiKey=023108a9c99043f18acff792c7e6bb89&width=400 400w, https://cdn.builder.io/api/v1/image/assets/TEMP/a6cb7f621cafd1e2da38f70b4566f0a74032c40ba318ab3a7818fa04b067bef3?apiKey=023108a9c99043f18acff792c7e6bb89&width=800 800w, https://cdn.builder.io/api/v1/image/assets/TEMP/a6cb7f621cafd1e2da38f70b4566f0a74032c40ba318ab3a7818fa04b067bef3?apiKey=023108a9c99043f18acff792c7e6bb89&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets/TEMP/a6cb7f621cafd1e2da38f70b4566f0a74032c40ba318ab3a7818fa04b067bef3?apiKey=023108a9c99043f18acff792c7e6bb89&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets/TEMP/a6cb7f621cafd1e2da38f70b4566f0a74032c40ba318ab3a7818fa04b067bef3?apiKey=023108a9c99043f18acff792c7e6bb89&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets/TEMP/a6cb7f621cafd1e2da38f70b4566f0a74032c40ba318ab3a7818fa04b067bef3?apiKey=023108a9c99043f18acff792c7e6bb89"
            class="self-center aspect-square w-[90px]" />
          <div class="mt-3">Nature Photography</div>
        </div>
        <div class="flex flex-col flex-1 px-4 py-9 bg-violet-50 rounded-2xl">
          <img loading="lazy"
            srcSet="https://cdn.builder.io/api/v1/image/assets/TEMP/d56f347a2a36f6d29a00c5d31212d5812bd44280a24264bef20d13dab325e490?apiKey=023108a9c99043f18acff792c7e6bb89&width=100 100w, https://cdn.builder.io/api/v1/image/assets/TEMP/d56f347a2a36f6d29a00c5d31212d5812bd44280a24264bef20d13dab325e490?apiKey=023108a9c99043f18acff792c7e6bb89&width=200 200w, https://cdn.builder.io/api/v1/image/assets/TEMP/d56f347a2a36f6d29a00c5d31212d5812bd44280a24264bef20d13dab325e490?apiKey=023108a9c99043f18acff792c7e6bb89&width=400 400w, https://cdn.builder.io/api/v1/image/assets/TEMP/d56f347a2a36f6d29a00c5d31212d5812bd44280a24264bef20d13dab325e490?apiKey=023108a9c99043f18acff792c7e6bb89&width=800 800w, https://cdn.builder.io/api/v1/image/assets/TEMP/d56f347a2a36f6d29a00c5d31212d5812bd44280a24264bef20d13dab325e490?apiKey=023108a9c99043f18acff792c7e6bb89&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets/TEMP/d56f347a2a36f6d29a00c5d31212d5812bd44280a24264bef20d13dab325e490?apiKey=023108a9c99043f18acff792c7e6bb89&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets/TEMP/d56f347a2a36f6d29a00c5d31212d5812bd44280a24264bef20d13dab325e490?apiKey=023108a9c99043f18acff792c7e6bb89&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets/TEMP/d56f347a2a36f6d29a00c5d31212d5812bd44280a24264bef20d13dab325e490?apiKey=023108a9c99043f18acff792c7e6bb89"
            class="self-center aspect-square w-[90px]" />
          <div class="mt-3">Micro Photography</div>
        </div>
        <div class="flex flex-col flex-1 px-4 py-9 bg-violet-50 rounded-2xl">
          <img loading="lazy"
            srcSet="https://cdn.builder.io/api/v1/image/assets/TEMP/377b209e1c180f530460d3dae5bff70e6272e8df3e3d4ef491b69b6af960f954?apiKey=023108a9c99043f18acff792c7e6bb89&width=100 100w, https://cdn.builder.io/api/v1/image/assets/TEMP/377b209e1c180f530460d3dae5bff70e6272e8df3e3d4ef491b69b6af960f954?apiKey=023108a9c99043f18acff792c7e6bb89&width=200 200w, https://cdn.builder.io/api/v1/image/assets/TEMP/377b209e1c180f530460d3dae5bff70e6272e8df3e3d4ef491b69b6af960f954?apiKey=023108a9c99043f18acff792c7e6bb89&width=400 400w, https://cdn.builder.io/api/v1/image/assets/TEMP/377b209e1c180f530460d3dae5bff70e6272e8df3e3d4ef491b69b6af960f954?apiKey=023108a9c99043f18acff792c7e6bb89&width=800 800w, https://cdn.builder.io/api/v1/image/assets/TEMP/377b209e1c180f530460d3dae5bff70e6272e8df3e3d4ef491b69b6af960f954?apiKey=023108a9c99043f18acff792c7e6bb89&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets/TEMP/377b209e1c180f530460d3dae5bff70e6272e8df3e3d4ef491b69b6af960f954?apiKey=023108a9c99043f18acff792c7e6bb89&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets/TEMP/377b209e1c180f530460d3dae5bff70e6272e8df3e3d4ef491b69b6af960f954?apiKey=023108a9c99043f18acff792c7e6bb89&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets/TEMP/377b209e1c180f530460d3dae5bff70e6272e8df3e3d4ef491b69b6af960f954?apiKey=023108a9c99043f18acff792c7e6bb89"
            class="self-center aspect-square w-[90px]" />
          <div class="mt-3">Aerial photography</div>
        </div>
        <div class="flex flex-col flex-1 px-4 py-9 bg-violet-50 rounded-2xl">
          <img loading="lazy"
            srcSet="https://cdn.builder.io/api/v1/image/assets/TEMP/ab1bee15e3a07728998b2b68ba8ceaadde19adb72950c8cf5279f1bdd474f4dc?apiKey=023108a9c99043f18acff792c7e6bb89&width=100 100w, https://cdn.builder.io/api/v1/image/assets/TEMP/ab1bee15e3a07728998b2b68ba8ceaadde19adb72950c8cf5279f1bdd474f4dc?apiKey=023108a9c99043f18acff792c7e6bb89&width=200 200w, https://cdn.builder.io/api/v1/image/assets/TEMP/ab1bee15e3a07728998b2b68ba8ceaadde19adb72950c8cf5279f1bdd474f4dc?apiKey=023108a9c99043f18acff792c7e6bb89&width=400 400w, https://cdn.builder.io/api/v1/image/assets/TEMP/ab1bee15e3a07728998b2b68ba8ceaadde19adb72950c8cf5279f1bdd474f4dc?apiKey=023108a9c99043f18acff792c7e6bb89&width=800 800w, https://cdn.builder.io/api/v1/image/assets/TEMP/ab1bee15e3a07728998b2b68ba8ceaadde19adb72950c8cf5279f1bdd474f4dc?apiKey=023108a9c99043f18acff792c7e6bb89&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets/TEMP/ab1bee15e3a07728998b2b68ba8ceaadde19adb72950c8cf5279f1bdd474f4dc?apiKey=023108a9c99043f18acff792c7e6bb89&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets/TEMP/ab1bee15e3a07728998b2b68ba8ceaadde19adb72950c8cf5279f1bdd474f4dc?apiKey=023108a9c99043f18acff792c7e6bb89&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets/TEMP/ab1bee15e3a07728998b2b68ba8ceaadde19adb72950c8cf5279f1bdd474f4dc?apiKey=023108a9c99043f18acff792c7e6bb89"
            class="self-center aspect-square w-[90px]" />
          <div class="mt-3">Food photography</div>
        </div>
      </div>
    </div>
    <div class="flex flex-col items-center px-10 mt-12 w-full max-w-[1320px] max-md:px-5 max-md:mt-10 max-md:max-w-full">
      <div class="text-4xl font-medium leading-10 text-zinc-900">Service</div>
      <div class="mt-3 text-lg leading-7 text-neutral-800 max-md:max-w-full">
        Learn from Industry Experts and Enhance Your Skills.
      </div>
      <div class="self-stretch mt-12 max-md:mt-10 max-md:max-w-full">
        <div class="flex gap-5 max-md:flex-col max-md:gap-0 max-md:">
          <div class="flex flex-col w-[33%] max-md:ml-0 max-md:w-full">
            <div
              class="flex flex-col grow px-4 pt-4 pb-12 w-full whitespace-nowrap bg-white rounded-lg border-solid border-[0.618px] border-black border-opacity-10 max-md:mt-10">
              <img loading="lazy"
                srcSet="https://cdn.builder.io/api/v1/image/assets/TEMP/1ee0e925c04adf1cd79cc54f7265c4aa9982dd32c9c3e33392c1ed5aa5e0c58e?apiKey=023108a9c99043f18acff792c7e6bb89&width=100 100w, https://cdn.builder.io/api/v1/image/assets/TEMP/1ee0e925c04adf1cd79cc54f7265c4aa9982dd32c9c3e33392c1ed5aa5e0c58e?apiKey=023108a9c99043f18acff792c7e6bb89&width=200 200w, https://cdn.builder.io/api/v1/image/assets/TEMP/1ee0e925c04adf1cd79cc54f7265c4aa9982dd32c9c3e33392c1ed5aa5e0c58e?apiKey=023108a9c99043f18acff792c7e6bb89&width=400 400w, https://cdn.builder.io/api/v1/image/assets/TEMP/1ee0e925c04adf1cd79cc54f7265c4aa9982dd32c9c3e33392c1ed5aa5e0c58e?apiKey=023108a9c99043f18acff792c7e6bb89&width=800 800w, https://cdn.builder.io/api/v1/image/assets/TEMP/1ee0e925c04adf1cd79cc54f7265c4aa9982dd32c9c3e33392c1ed5aa5e0c58e?apiKey=023108a9c99043f18acff792c7e6bb89&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets/TEMP/1ee0e925c04adf1cd79cc54f7265c4aa9982dd32c9c3e33392c1ed5aa5e0c58e?apiKey=023108a9c99043f18acff792c7e6bb89&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets/TEMP/1ee0e925c04adf1cd79cc54f7265c4aa9982dd32c9c3e33392c1ed5aa5e0c58e?apiKey=023108a9c99043f18acff792c7e6bb89&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets/TEMP/1ee0e925c04adf1cd79cc54f7265c4aa9982dd32c9c3e33392c1ed5aa5e0c58e?apiKey=023108a9c99043f18acff792c7e6bb89"
                class="w-full aspect-[1.56]" /><img loading="lazy"
                src="https://cdn.builder.io/api/v1/image/assets/TEMP/513fe6fd8809966c0c53020be6ec564b075edbd0d140de803e9d13c5c79de42e?apiKey=023108a9c99043f18acff792c7e6bb89"
                class="mt-4 aspect-[6.25] w-[97px]" />
              <div class="mt-1 text-lg font-semibold leading-7 text-neutral-800">
                Family Photoshoot
              </div>
              <div class="mt-2 text-base leading-6 text-ellipsis text-neutral-600">
                Contrary to popular belief, Lorem Ipsum is not simply random
                text. It has roots in a piece of classical Latin literature from
                45 BC, making it over 2000 years old. Richard McClintock, a
                Latin professor at Hampden-Sydney College in Virginia, looked up
                one of the more obscure Latin words, consectetur, from a Lorem
                Ipsum passage, and going through the cites of the word in
                classical literature, discovered the undoubtable source. Lorem
                Ipsum comes from sections 1.10.32 and 1.10.33 of &quot;de
                Finibus Bonorum et Malorum&quot; (The Extremes of Good and Evil)
                by Cicero, written in 45 BC. This book is a treatise on the
                theory of ethics, very popular during the Renaissance. The first
                line of Lorem Ipsum, &quot;Lorem ipsum dolor sit amet..&quot;,
                comes from a line in section 1.10.32.<br />
              </div>
            </div>
          </div>
          <div class="flex flex-col ml-5 w-[33%] max-md:ml-0 max-md:w-full">
            <div
              class="flex flex-col grow px-4 pt-4 pb-12 w-full whitespace-nowrap bg-white rounded-lg border-solid border-[0.618px] border-black border-opacity-10 max-md:mt-10">
              <img loading="lazy"
                srcSet="https://cdn.builder.io/api/v1/image/assets/TEMP/9aba67045a8dcd683cc497fdc44eebece22b6b092b320dcae0dfac9bfd758843?apiKey=023108a9c99043f18acff792c7e6bb89&width=100 100w, https://cdn.builder.io/api/v1/image/assets/TEMP/9aba67045a8dcd683cc497fdc44eebece22b6b092b320dcae0dfac9bfd758843?apiKey=023108a9c99043f18acff792c7e6bb89&width=200 200w, https://cdn.builder.io/api/v1/image/assets/TEMP/9aba67045a8dcd683cc497fdc44eebece22b6b092b320dcae0dfac9bfd758843?apiKey=023108a9c99043f18acff792c7e6bb89&width=400 400w, https://cdn.builder.io/api/v1/image/assets/TEMP/9aba67045a8dcd683cc497fdc44eebece22b6b092b320dcae0dfac9bfd758843?apiKey=023108a9c99043f18acff792c7e6bb89&width=800 800w, https://cdn.builder.io/api/v1/image/assets/TEMP/9aba67045a8dcd683cc497fdc44eebece22b6b092b320dcae0dfac9bfd758843?apiKey=023108a9c99043f18acff792c7e6bb89&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets/TEMP/9aba67045a8dcd683cc497fdc44eebece22b6b092b320dcae0dfac9bfd758843?apiKey=023108a9c99043f18acff792c7e6bb89&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets/TEMP/9aba67045a8dcd683cc497fdc44eebece22b6b092b320dcae0dfac9bfd758843?apiKey=023108a9c99043f18acff792c7e6bb89&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets/TEMP/9aba67045a8dcd683cc497fdc44eebece22b6b092b320dcae0dfac9bfd758843?apiKey=023108a9c99043f18acff792c7e6bb89"
                class="w-full aspect-[1.56]" /><img loading="lazy"
                src="https://cdn.builder.io/api/v1/image/assets/TEMP/a60eb65abba55009f1d20b92f8fca2c399fd1bb06cf7e09cc18384d7bfc19880?apiKey=023108a9c99043f18acff792c7e6bb89"
                class="mt-4 aspect-[6.25] w-[97px]" />
              <div class="mt-1 text-lg font-semibold leading-7 text-neutral-800">
                Nature Photoshoot
              </div>
              <div class="mt-2 text-base leading-6 text-ellipsis text-neutral-600">
                Contrary to popular belief, Lorem Ipsum is not simply random
                text. It has roots in a piece of classical Latin literature from
                45 BC, making it over 2000 years old. Richard McClintock, a
                Latin professor at Hampden-Sydney College in Virginia, looked up
                one of the more obscure Latin words, consectetur, from a Lorem
                Ipsum passage, and going through the cites of the word in
                classical literature, discovered the undoubtable source. Lorem
                Ipsum comes from sections 1.10.32 and 1.10.33 of &quot;de
                Finibus Bonorum et Malorum&quot; (The Extremes of Good and Evil)
                by Cicero, written in 45 BC. This book is a treatise on the
                theory of ethics, very popular during the Renaissance. The first
                line of Lorem Ipsum, &quot;Lorem ipsum dolor sit amet..&quot;,
                comes from a line in section 1.10.32.<br />
              </div>
            </div>
          </div>
          <div class="flex flex-col ml-5 w-[33%] max-md:ml-0 max-md:w-full">
            <div
              class="flex flex-col grow px-4 pt-4 pb-12 w-full whitespace-nowrap bg-white rounded-lg border-solid border-[0.618px] border-black border-opacity-10 max-md:mt-10">
              <img loading="lazy"
                srcSet="https://cdn.builder.io/api/v1/image/assets/TEMP/ef4c1c2057bf4bee58aa876f065161065d362a26c8cf83a00ec74ec85f7d1058?apiKey=023108a9c99043f18acff792c7e6bb89&width=100 100w, https://cdn.builder.io/api/v1/image/assets/TEMP/ef4c1c2057bf4bee58aa876f065161065d362a26c8cf83a00ec74ec85f7d1058?apiKey=023108a9c99043f18acff792c7e6bb89&width=200 200w, https://cdn.builder.io/api/v1/image/assets/TEMP/ef4c1c2057bf4bee58aa876f065161065d362a26c8cf83a00ec74ec85f7d1058?apiKey=023108a9c99043f18acff792c7e6bb89&width=400 400w, https://cdn.builder.io/api/v1/image/assets/TEMP/ef4c1c2057bf4bee58aa876f065161065d362a26c8cf83a00ec74ec85f7d1058?apiKey=023108a9c99043f18acff792c7e6bb89&width=800 800w, https://cdn.builder.io/api/v1/image/assets/TEMP/ef4c1c2057bf4bee58aa876f065161065d362a26c8cf83a00ec74ec85f7d1058?apiKey=023108a9c99043f18acff792c7e6bb89&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets/TEMP/ef4c1c2057bf4bee58aa876f065161065d362a26c8cf83a00ec74ec85f7d1058?apiKey=023108a9c99043f18acff792c7e6bb89&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets/TEMP/ef4c1c2057bf4bee58aa876f065161065d362a26c8cf83a00ec74ec85f7d1058?apiKey=023108a9c99043f18acff792c7e6bb89&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets/TEMP/ef4c1c2057bf4bee58aa876f065161065d362a26c8cf83a00ec74ec85f7d1058?apiKey=023108a9c99043f18acff792c7e6bb89"
                class="w-full aspect-[1.56]" /><img loading="lazy"
                src="https://cdn.builder.io/api/v1/image/assets/TEMP/1ac3fbfe6db5bbb6b2b0d901f96d9d468ad7b080ee60c5720a77917d83866619?apiKey=023108a9c99043f18acff792c7e6bb89"
                class="mt-4 aspect-[6.25] w-[97px]" />
              <div class="mt-1 text-lg font-semibold leading-7 text-neutral-800">
                Fashion Consultation
              </div>
              <div class="mt-2 text-base leading-6 text-ellipsis text-neutral-600">
                Contrary to popular belief, Lorem Ipsum is not simply random
                text. It has roots in a piece of classical Latin literature from
                45 BC, making it over 2000 years old. Richard McClintock, a
                Latin professor at Hampden-Sydney College in Virginia, looked up
                one of the more obscure Latin words, consectetur, from a Lorem
                Ipsum passage, and going through the cites of the word in
                classical literature, discovered the undoubtable source. Lorem
                Ipsum comes from sections 1.10.32 and 1.10.33 of &quot;de
                Finibus Bonorum et Malorum&quot; (The Extremes of Good and Evil)
                by Cicero, written in 45 BC. This book is a treatise on the
                theory of ethics, very popular during the Renaissance. The first
                line of Lorem Ipsum, &quot;Lorem ipsum dolor sit amet..&quot;,
                comes from a line in section 1.10.32.<br />
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="mt-8 w-14 h-4 bg-white rounded-xl"></div>
    </div>
    <div
      class="flex overflow-hidden relative flex-col items-start self-stretch px-20 py-12 mt-12 w-full leading-[100%] min-h-[391px] max-md:px-5 max-md:mt-10 max-md:max-w-full">
      <img loading="lazy"
        srcSet="https://cdn.builder.io/api/v1/image/assets/TEMP/507330240e4cbae8d4c1f968a49853249b8a65fb6f56f4567d7f099e098d729d?apiKey=023108a9c99043f18acff792c7e6bb89&width=100 100w, https://cdn.builder.io/api/v1/image/assets/TEMP/507330240e4cbae8d4c1f968a49853249b8a65fb6f56f4567d7f099e098d729d?apiKey=023108a9c99043f18acff792c7e6bb89&width=200 200w, https://cdn.builder.io/api/v1/image/assets/TEMP/507330240e4cbae8d4c1f968a49853249b8a65fb6f56f4567d7f099e098d729d?apiKey=023108a9c99043f18acff792c7e6bb89&width=400 400w, https://cdn.builder.io/api/v1/image/assets/TEMP/507330240e4cbae8d4c1f968a49853249b8a65fb6f56f4567d7f099e098d729d?apiKey=023108a9c99043f18acff792c7e6bb89&width=800 800w, https://cdn.builder.io/api/v1/image/assets/TEMP/507330240e4cbae8d4c1f968a49853249b8a65fb6f56f4567d7f099e098d729d?apiKey=023108a9c99043f18acff792c7e6bb89&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets/TEMP/507330240e4cbae8d4c1f968a49853249b8a65fb6f56f4567d7f099e098d729d?apiKey=023108a9c99043f18acff792c7e6bb89&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets/TEMP/507330240e4cbae8d4c1f968a49853249b8a65fb6f56f4567d7f099e098d729d?apiKey=023108a9c99043f18acff792c7e6bb89&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets/TEMP/507330240e4cbae8d4c1f968a49853249b8a65fb6f56f4567d7f099e098d729d?apiKey=023108a9c99043f18acff792c7e6bb89"
        class="object-cover absolute inset-0 size-full" />
      <div class="relative mt-12 ml-4 text-5xl font-medium text-white max-md:mt-10 max-md:max-w-full max-md:text-4xl">
        Special Offer
      </div>
      <div class="relative mt-4 ml-4 text-2xl font-semibold text-stone-300 w-[760px] max-md:max-w-full">
        Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod
        tempor incididunt ut labore et dolore magna aliqua.
      </div>
      <div
        class="relative justify-center px-10 py-5 mt-7 mb-12 ml-4 text-lg font-bold text-center whitespace-nowrap bg-blue-600 shadow-sm rounded-[30px] text-white text-opacity-90 max-md:px-5 max-md:mb-10 max-md:ml-2.5">
        Book Now
      </div>
    </div>
    <div
      class="flex flex-col self-stretch px-16 pt-8 pb-12 mt-12 w-full bg-white max-md:px-5 max-md:mt-10 max-md:max-w-full">
      <div class="flex flex-col items-center mx-10 mb-11 max-md:mr-2.5 max-md:mb-10 max-md:max-w-full">
        <div class="text-4xl font-medium leading-10 text-zinc-900">
          Testimonial
        </div>
        <div class="mt-3 text-lg leading-7 text-neutral-800 max-md:max-w-full">
          Learn from Industry Experts and Enhance Your Skills.
        </div>
        <div class="self-stretch mt-12 max-md:mt-10 max-md:max-w-full">
          <div class="flex gap-5 max-md:flex-col max-md:gap-0 max-md:">
            <div class="flex flex-col w-[33%] max-md:ml-0 max-md:w-full">
              <div class="flex flex-col grow pt-9 max-md:mt-10">
                <div class="flex flex-col items-center px-7 pb-8 rounded-3xl bg-neutral-100 max-md:px-5">
                  <div class="flex z-10 justify-center items-center px-3 mt-0 w-24 h-24 bg-white rounded-full">
                    <img loading="lazy"
                      srcSet="https://cdn.builder.io/api/v1/image/assets/TEMP/0c9ebdd08e2ad7af63eaa81dbc6dac6184e14f6a21f13170eeab06d0ad4acab2?apiKey=023108a9c99043f18acff792c7e6bb89&width=100 100w, https://cdn.builder.io/api/v1/image/assets/TEMP/0c9ebdd08e2ad7af63eaa81dbc6dac6184e14f6a21f13170eeab06d0ad4acab2?apiKey=023108a9c99043f18acff792c7e6bb89&width=200 200w, https://cdn.builder.io/api/v1/image/assets/TEMP/0c9ebdd08e2ad7af63eaa81dbc6dac6184e14f6a21f13170eeab06d0ad4acab2?apiKey=023108a9c99043f18acff792c7e6bb89&width=400 400w, https://cdn.builder.io/api/v1/image/assets/TEMP/0c9ebdd08e2ad7af63eaa81dbc6dac6184e14f6a21f13170eeab06d0ad4acab2?apiKey=023108a9c99043f18acff792c7e6bb89&width=800 800w, https://cdn.builder.io/api/v1/image/assets/TEMP/0c9ebdd08e2ad7af63eaa81dbc6dac6184e14f6a21f13170eeab06d0ad4acab2?apiKey=023108a9c99043f18acff792c7e6bb89&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets/TEMP/0c9ebdd08e2ad7af63eaa81dbc6dac6184e14f6a21f13170eeab06d0ad4acab2?apiKey=023108a9c99043f18acff792c7e6bb89&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets/TEMP/0c9ebdd08e2ad7af63eaa81dbc6dac6184e14f6a21f13170eeab06d0ad4acab2?apiKey=023108a9c99043f18acff792c7e6bb89&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets/TEMP/0c9ebdd08e2ad7af63eaa81dbc6dac6184e14f6a21f13170eeab06d0ad4acab2?apiKey=023108a9c99043f18acff792c7e6bb89"
                      class="w-full rounded-full aspect-[0.99]" />
                  </div>
                  <div class="mt-2.5 text-2xl font-semibold leading-5 text-center whitespace-nowrap text-violet-950">
                    Shivam Kumar
                  </div>
                  <div class="mt-3.5 text-lg font-bold leading-5 text-center whitespace-nowrap text-zinc-500">
                    CEO & Founder
                  </div>
                  <div class="self-stretch mt-7 text-lg leading-8 text-slate-500">
                    “A visual guide could be wireframe, creative composition,
                    or information architecture. A device that enables
                    collaboration will lessen the chance of work having to be
                    completely redone.”
                  </div>
                </div>
              </div>
            </div>
            <div class="flex flex-col ml-5 w-[33%] max-md:ml-0 max-md:w-full">
              <div class="flex flex-col grow pt-9 max-md:mt-10">
                <div class="flex flex-col items-center px-7 pb-8 rounded-3xl bg-neutral-100 max-md:px-5">
                  <div class="flex z-10 justify-center items-center px-3 mt-0 w-24 h-24 bg-white rounded-full">
                    <img loading="lazy"
                      srcSet="https://cdn.builder.io/api/v1/image/assets/TEMP/eaa66577cccb5e0ef55e6539bf0f64b5c740daf62ecb85013ce6178d6dc8acce?apiKey=023108a9c99043f18acff792c7e6bb89&width=100 100w, https://cdn.builder.io/api/v1/image/assets/TEMP/eaa66577cccb5e0ef55e6539bf0f64b5c740daf62ecb85013ce6178d6dc8acce?apiKey=023108a9c99043f18acff792c7e6bb89&width=200 200w, https://cdn.builder.io/api/v1/image/assets/TEMP/eaa66577cccb5e0ef55e6539bf0f64b5c740daf62ecb85013ce6178d6dc8acce?apiKey=023108a9c99043f18acff792c7e6bb89&width=400 400w, https://cdn.builder.io/api/v1/image/assets/TEMP/eaa66577cccb5e0ef55e6539bf0f64b5c740daf62ecb85013ce6178d6dc8acce?apiKey=023108a9c99043f18acff792c7e6bb89&width=800 800w, https://cdn.builder.io/api/v1/image/assets/TEMP/eaa66577cccb5e0ef55e6539bf0f64b5c740daf62ecb85013ce6178d6dc8acce?apiKey=023108a9c99043f18acff792c7e6bb89&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets/TEMP/eaa66577cccb5e0ef55e6539bf0f64b5c740daf62ecb85013ce6178d6dc8acce?apiKey=023108a9c99043f18acff792c7e6bb89&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets/TEMP/eaa66577cccb5e0ef55e6539bf0f64b5c740daf62ecb85013ce6178d6dc8acce?apiKey=023108a9c99043f18acff792c7e6bb89&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets/TEMP/eaa66577cccb5e0ef55e6539bf0f64b5c740daf62ecb85013ce6178d6dc8acce?apiKey=023108a9c99043f18acff792c7e6bb89"
                      class="w-full rounded-full aspect-square" />
                  </div>
                  <div class="mt-2.5 text-2xl font-semibold leading-5 text-center whitespace-nowrap text-violet-950">
                    Pawan Kumar
                  </div>
                  <div class="mt-3.5 text-lg font-bold leading-5 text-center text-zinc-500">
                    CTO
                  </div>
                  <div class="self-stretch mt-7 text-lg leading-8 text-slate-500">
                    “A visual guide could be a wireframe, creative composition,
                    or information architecture. A device that enables
                    collaboration will lessen the chance of work having to be
                    completely redone.”
                  </div>
                </div>
              </div>
            </div>
            <div class="flex flex-col ml-5 w-[33%] max-md:ml-0 max-md:w-full">
              <div class="flex flex-col grow pt-9 max-md:mt-10">
                <div class="flex flex-col items-center px-7 pb-8 rounded-3xl bg-neutral-100 max-md:px-5">
                  <div class="flex z-10 justify-center items-center px-3 mt-0 w-24 h-24 bg-white rounded-full">
                    <img loading="lazy"
                      srcSet="https://cdn.builder.io/api/v1/image/assets/TEMP/6dc86422a9362cc6f828dcbe46ec2d3c4941ea0a7d64ab10acdfe0967180bd4f?apiKey=023108a9c99043f18acff792c7e6bb89&width=100 100w, https://cdn.builder.io/api/v1/image/assets/TEMP/6dc86422a9362cc6f828dcbe46ec2d3c4941ea0a7d64ab10acdfe0967180bd4f?apiKey=023108a9c99043f18acff792c7e6bb89&width=200 200w, https://cdn.builder.io/api/v1/image/assets/TEMP/6dc86422a9362cc6f828dcbe46ec2d3c4941ea0a7d64ab10acdfe0967180bd4f?apiKey=023108a9c99043f18acff792c7e6bb89&width=400 400w, https://cdn.builder.io/api/v1/image/assets/TEMP/6dc86422a9362cc6f828dcbe46ec2d3c4941ea0a7d64ab10acdfe0967180bd4f?apiKey=023108a9c99043f18acff792c7e6bb89&width=800 800w, https://cdn.builder.io/api/v1/image/assets/TEMP/6dc86422a9362cc6f828dcbe46ec2d3c4941ea0a7d64ab10acdfe0967180bd4f?apiKey=023108a9c99043f18acff792c7e6bb89&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets/TEMP/6dc86422a9362cc6f828dcbe46ec2d3c4941ea0a7d64ab10acdfe0967180bd4f?apiKey=023108a9c99043f18acff792c7e6bb89&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets/TEMP/6dc86422a9362cc6f828dcbe46ec2d3c4941ea0a7d64ab10acdfe0967180bd4f?apiKey=023108a9c99043f18acff792c7e6bb89&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets/TEMP/6dc86422a9362cc6f828dcbe46ec2d3c4941ea0a7d64ab10acdfe0967180bd4f?apiKey=023108a9c99043f18acff792c7e6bb89"
                      class="w-full rounded-full aspect-square" />
                  </div>
                  <div class="mt-2.5 text-2xl font-semibold leading-5 text-center whitespace-nowrap text-violet-950">
                    Priya Roy
                  </div>
                  <div class="mt-2 text-lg font-bold leading-5 text-center text-zinc-500">
                    COO
                  </div>
                  <div class="self-stretch mt-7 text-lg leading-8 text-slate-500">
                    “A visual guide could be a wireframe, creative composition,
                    or information architecture. A device that enables
                    collaboration will lessen the chance of work having to be
                    completely redone.”
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="mt-8 w-14 h-4 bg-white rounded-xl"></div>
      </div>
    </div>
    <div class="flex z-10 flex-col self-stretch px-20 pt-12 pb-5 mt-0 w-full bg-violet-50 max-md:px-5 max-md:max-w-full">
      <div class="flex gap-5 justify-between items-start ml-5 w-full max-md:flex-wrap max-md:max-w-full">
        <div class="flex flex-col pt-2.5 basis-0">
          <div class="self-start text-4xl font-medium leading-10 text-blue-600">
            JIVIKA
          </div>
          <div class="mt-10 text-lg leading-8 text-slate-400">
            Lorem ipsum dolor sit amet consectetur adipiscing elit aliquam
            mauris sed ma
          </div>
          <div class="flex gap-4 pr-20 mt-10 max-md:pr-5">
            <img loading="lazy"
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/7123419bff090c09c6c87df1aeb395a97eb673b8cb986da056e5d66ac05ae708?apiKey=023108a9c99043f18acff792c7e6bb89"
              class="w-9 aspect-square" /><img loading="lazy"
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/a1c216b95adee59800ded2bc233f7df625d558d80d64471ddf513e018ce256fb?apiKey=023108a9c99043f18acff792c7e6bb89"
              class="w-9 aspect-square" /><img loading="lazy"
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/acf6a7660dce5e85d04e6312114852f4ccaf62ca448c71c8acf3fbc76c98eb1f?apiKey=023108a9c99043f18acff792c7e6bb89"
              class="w-9 aspect-square" /><img loading="lazy"
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/50aa19062c2af9ca66e3f242555c79407d191a5e76af6f334928d59fe4c7f786?apiKey=023108a9c99043f18acff792c7e6bb89"
              class="w-9 aspect-square" /><img loading="lazy"
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/d8ffe5f2027e743f150101c36d6b2422e826a357f5872f3a7b4c859dc316de18?apiKey=023108a9c99043f18acff792c7e6bb89"
              class="w-9 aspect-square" />
          </div>
        </div>
        <div class="self-stretch max-md:max-w-full">
          <div class="flex gap-5 max-md:flex-col max-md:gap-0 max-md:">
            <div class="flex flex-col w-[58%] max-md:ml-0 max-md:w-full">
              <div class="flex grow gap-5 justify-between text-base font-medium leading-6 max-md:mt-10">
                <div class="flex flex-col flex-1 text-neutral-400">
                  <div class="text-xl leading-8 text-blue-600">Service</div>
                  <div class="mt-6 text-center">Nature Photography</div>
                  <div class="mt-4 text-center">Clothier</div>
                  <div class="mt-4 text-center">Personal Shopper</div>
                  <div class="mt-4 text-center">Personal Stylist</div>
                  <div class="mt-4 text-center">Micro Photography</div>
                  <div class="mt-2.5 text-center">Family Photography</div>
                </div>
                <div class="flex flex-col flex-1 self-start pb-1.5 text-blue-600">
                  <div class="text-xl leading-8">Quick Link</div>
                  <div class="mt-6 text-center text-neutral-400">About</div>
                  <div class="flex gap-1.5 justify-between py-1.5 mt-2.5 text-center whitespace-nowrap">
                    <img loading="lazy"
                      src="https://cdn.builder.io/api/v1/image/assets/TEMP/0af0a5ce75c949e4d0af9d91c4a991bd74e549638334be963faa7d977270cf71?apiKey=023108a9c99043f18acff792c7e6bb89"
                      class="my-auto w-5 aspect-square" />
                    <div class="flex-auto">Contact</div>
                  </div>
                  <div class="mt-2.5 text-center text-neutral-400">Blog</div>
                </div>
              </div>
            </div>
            <div class="flex flex-col ml-5 w-[42%] max-md:ml-0 max-md:w-full">
              <div class="flex flex-col pb-2.5 text-xl font-medium text-blue-600 max-md:mt-10">
                <div>Visite Addreas</div>
                <img loading="lazy"
                  srcSet="https://cdn.builder.io/api/v1/image/assets/TEMP/dc893b007c69d8b38d1a7ffd593d37e56c3e5ff03e2db2a01f1d9bd0ab0003dc?apiKey=023108a9c99043f18acff792c7e6bb89&width=100 100w, https://cdn.builder.io/api/v1/image/assets/TEMP/dc893b007c69d8b38d1a7ffd593d37e56c3e5ff03e2db2a01f1d9bd0ab0003dc?apiKey=023108a9c99043f18acff792c7e6bb89&width=200 200w, https://cdn.builder.io/api/v1/image/assets/TEMP/dc893b007c69d8b38d1a7ffd593d37e56c3e5ff03e2db2a01f1d9bd0ab0003dc?apiKey=023108a9c99043f18acff792c7e6bb89&width=400 400w, https://cdn.builder.io/api/v1/image/assets/TEMP/dc893b007c69d8b38d1a7ffd593d37e56c3e5ff03e2db2a01f1d9bd0ab0003dc?apiKey=023108a9c99043f18acff792c7e6bb89&width=800 800w, https://cdn.builder.io/api/v1/image/assets/TEMP/dc893b007c69d8b38d1a7ffd593d37e56c3e5ff03e2db2a01f1d9bd0ab0003dc?apiKey=023108a9c99043f18acff792c7e6bb89&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets/TEMP/dc893b007c69d8b38d1a7ffd593d37e56c3e5ff03e2db2a01f1d9bd0ab0003dc?apiKey=023108a9c99043f18acff792c7e6bb89&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets/TEMP/dc893b007c69d8b38d1a7ffd593d37e56c3e5ff03e2db2a01f1d9bd0ab0003dc?apiKey=023108a9c99043f18acff792c7e6bb89&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets/TEMP/dc893b007c69d8b38d1a7ffd593d37e56c3e5ff03e2db2a01f1d9bd0ab0003dc?apiKey=023108a9c99043f18acff792c7e6bb89"
                  class="mt-6 w-full aspect-[1.43]" />
              </div>
            </div>
          </div>
        </div>
        <div class="flex justify-center items-center aspect-square">
          <img loading="lazy"
            srcSet="https://cdn.builder.io/api/v1/image/assets/TEMP/e45bdf0b24747d9f06e00111e5f6d8eaa2b604cd70c0c1f59134eea272abae59?apiKey=023108a9c99043f18acff792c7e6bb89&width=100 100w, https://cdn.builder.io/api/v1/image/assets/TEMP/e45bdf0b24747d9f06e00111e5f6d8eaa2b604cd70c0c1f59134eea272abae59?apiKey=023108a9c99043f18acff792c7e6bb89&width=200 200w, https://cdn.builder.io/api/v1/image/assets/TEMP/e45bdf0b24747d9f06e00111e5f6d8eaa2b604cd70c0c1f59134eea272abae59?apiKey=023108a9c99043f18acff792c7e6bb89&width=400 400w, https://cdn.builder.io/api/v1/image/assets/TEMP/e45bdf0b24747d9f06e00111e5f6d8eaa2b604cd70c0c1f59134eea272abae59?apiKey=023108a9c99043f18acff792c7e6bb89&width=800 800w, https://cdn.builder.io/api/v1/image/assets/TEMP/e45bdf0b24747d9f06e00111e5f6d8eaa2b604cd70c0c1f59134eea272abae59?apiKey=023108a9c99043f18acff792c7e6bb89&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets/TEMP/e45bdf0b24747d9f06e00111e5f6d8eaa2b604cd70c0c1f59134eea272abae59?apiKey=023108a9c99043f18acff792c7e6bb89&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets/TEMP/e45bdf0b24747d9f06e00111e5f6d8eaa2b604cd70c0c1f59134eea272abae59?apiKey=023108a9c99043f18acff792c7e6bb89&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets/TEMP/e45bdf0b24747d9f06e00111e5f6d8eaa2b604cd70c0c1f59134eea272abae59?apiKey=023108a9c99043f18acff792c7e6bb89"
            class="rounded-full aspect-square stroke-[2px] w-[42px]" />
        </div>
      </div>
      <div class="self-center mt-20 text-lg leading-8 text-center text-gray-400 underline max-md:mt-10 max-md:max-w-full">
        <span class="leading-5 text-slate-500">Copyright © 2023 pawan_design | All Rights Reserved | </span><span
          class="text-gray-400 underline">Terms and Conditions </span><span class="leading-5 text-slate-500">|
        </span><span class="text-gray-400 underline">Privacy Policy</span>
      </div>
    </div>
  </div>
</template>
